import logging
import pandas as pd
import numpy as np
import config

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

class DataPreprocessor:
    def __init__(self, target_col: str = config.TARGET_COL, horizon: int = config.HORIZON):
        self.target_col = target_col
        self.horizon = horizon

    def clean_data(self, df: pd.DataFrame) -> pd.DataFrame:
        """Cleans stock data by sorting, removing duplicates, and handling multi-index formats."""
        df = df.copy()
        
        # Flatten MultiIndex columns if generated by yfinance
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = [col[0] for col in df.columns]
            
        # Ensure index is datetime and sorted
        df.index = pd.to_datetime(df.index)
        df = df.sort_index()
        
        # Drop duplicates
        initial_len = len(df)
        df = df[~df.index.duplicated(keep='first')]
        if len(df) < initial_len:
            logger.info(f"Dropped {initial_len - len(df)} duplicate rows.")

        # Standardize column names to lowercase
        df.columns = [col.lower() for col in df.columns]
        return df

    def create_target(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Creates a binary classification target: 
        1 if price increases 'horizon' days from now, 0 otherwise.
        """
        df = df.copy()
        if 'close' not in df.columns:
            raise KeyError("Dataframe must contain a 'close' column to generate targets.")
            
        # Shift the close price backward to look into the future
        future_close = df['close'].shift(-self.horizon)
        
        # Target: 1 if future price > current price, else 0
        df[self.target_col] = (future_close > df['close']).astype(int)
        
        # Remove the last 'horizon' rows because their future target is unknown (NaN)
        df = df.iloc[:-self.horizon]
        
        logger.info(f"Target variable '{self.target_col}' created. Final row count: {len(df)}")
        return df

if __name__ == "__main__":
    # Test Preprocessing pipeline locally
    raw_data_path = config.DATA_DIR / "raw_stock_data.csv"
    if raw_data_path.exists():
        raw_df = pd.read_csv(raw_data_path, index_col=0)
        preprocessor = DataPreprocessor()
        
        cleaned_df = preprocessor.clean_data(raw_df)
        processed_df = preprocessor.create_target(cleaned_df)
        print(processed_df.tail())
    else:
        logger.error("Raw data file not found. Run data_loader.py first.")